airport_dbt:
  target: prod
  outputs:
    prod:
      type: databricks
      catalog: airport_project
      schema: flights_gold
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_DBT_ACCESS_KEY') }}"
      threads: 4